apiVersion: v1
kind: Service
metadata:
  name: {{ template "argocd_application.fullname" . }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "jenkins.name" . }}
    release: {{ .Release.Name }}

